export const AccountModel = "Account"
export const ResetCodeModel = "ResetCode"
export const SpotifyArtistsModel = "SpotifyArtists"
export const SpotifyTracksModel = "SpotifyTracks"
export const SpotifyDataModel = "SpotifyData"